heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running a WordPress.

parameters:

  flavor:
    label: Web Server Flavor
    description: Cloud Server flavor to use on all web servers
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  image:
    label: Operating System
    description: Server image used for all web servers
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 13.04 LTS (Saucy Salamander)
      - Ubuntu 14.04 LTS (Trusty Tahr)
      description: Must be a supported operating system.

resources:

  ssh_keypair:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  webserver:
    type: Rackspace::Cloud::Server
    properties:
      name: drupal_web_server
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_keypair }

    