heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running a WordPress.

parameters:

  # Web server parameters
  name:
    label: Web Server Name
    description: Cloud Server name
    type: string

  flavor:
    label: Web Server Flavor
    description: Cloud Server flavor to use on all web servers
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  image:
    label: Operating System
    description: Server image used for all web servers
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string

  ssh_private_key:
    description: Private SSH key
    type: string
    default: false

  # Drupal database parameters
  db_hostname:
    description: Hostname for the database instance
    type: string
    default: localhost

  db_name:
    description: Database name
    type: string
    default: drupal_db

  db_username:
    description: Username for the database
    type: string
    default: drupal_db_user
    constraints:
    - allowed_pattern: "^(.){1,16}$"
      description: |
        Must be shorter than 16 characters, this is due to MySQL's maximum
        username length.

  db_password:
    description: Password for the database user with access to the Drupal database
    type: string

  # Chef configuration parameters
  kitchen:
    description: URL for the kitchen to use, fetched using git
    type: string
    default: https://github.com/ycombinator/drupal-multi

  chef_version:
    description: Version of chef client to use
    type: string
    default: 11.12.4

resources:

  webserver:
    type: Rackspace::Cloud::Server
    properties:
      name: { get_param: name }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }

  webserver_setup:
    type: OS::Heat::ChefSolo
    depends_on: webserver
    properties:
      host: { get_attr: [webserver, accessIPv4] }
      username: root
      private_key: { get_param: ssh_private_key }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        fqdn: { get_param: "OS::stack_name" }
        drupal:
          version: 7.28
          db:
            host: { get_param: db_hostname }
            database: { get_param: db_name }
            user: { get_param: db_username }
            password: { get_param: db_password }
        run_list: ["recipe[apt]",
                   "recipe[drupal]"]

outputs:

  private_ip:
    value: { get_attr: [webserver, privateIPv4] }
    